### ISSUE TITLE
Movement in demo program is framerate dependant

### ISSUE THREAD

**Issue by Ybalrid** [Ybalrid/BtOgre2#12]
This needs to be fixed.

**Comment by Ybalrid** [comment]
Actually, it's not like it's really important...

**Comment by screwt** [comment]
I'm thinking about that, but the momvement are handled here right?

https://github.com/Ybalrid/BtOgre2/blob/f371f9ce52ba234a20c4f3b9a842a19ec94161d4/demo/main.cpp#L476

end because of the :
https://github.com/Ybalrid/BtOgre2/blob/f371f9ce52ba234a20c4f3b9a842a19ec94161d4/demo/main.cpp#L472-L473

That makes it FPS independent does it?

**Comment by Ybalrid** [comment]
I actually do not remember what thing thing was refering exactly, but I think it's more about the FPS camera movement (WASD+mouselook) 

Simulation time is frame-rate independent yes.

**Comment by Ybalrid** [comment]
TBH, that demo program is a huge mess anyway, it's an old Ogre 1.7 thing that was in the original repo that I re-hacked together so that it could run, but graphics are horrible. I have no time to redo something "clean", but I'll accept contribution of any small-ish program that would demonstrate how to use the lib API
